# based on https://github.com/marketplace/actions/build-and-push-docker-images

name: Build Docker Image
on:
  push:
    branches: [ "main" ]
    paths:
      - phira-mp-server/Dockerfile
  pull_request:
    branches: [ "main" ]
    paths:
      - phira-mp-server/Dockerfile
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: deanvry/phira-mp-server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./phira-mp-server
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
